# NATS WebSocket gateway (for browser -> NATS communication)
apiVersion: v1
kind: Service
metadata:
  name: nats-gateway-service
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.websocket.port }}
    nodePort: {{ .Values.gatewayNodePort }}
