# Internal NATS service (for ingester -> NATS communication)
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  ports:
  - port: 4222
