# Monitoring Stack (Grafana + Prometheus)
apiVersion: v2
name: monitoring
description: Cluster monitoring with Grafana dashboards and Prometheus metrics
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "65.8.1"
    repository: https://prometheus-community.github.io/helm-charts
