apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "influxdb.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8086
      targetPort: 8086
      name: http
